In [2]:
import numpy as np


npz_path = '/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/datasets_AFTERNOON/visual_data/AFTERNOON/test/AFTERNOON_00001.npz'

# npz = np.load(npz_path)['data']
# for npy in npz:
#     print(npy)

with np.load(npz_path) as data:
    data = data['data']
    print(data)

[[[116 115 114 ... 102 103 109]
  [115 114 113 ... 102 102 107]
  [114 113 113 ... 102 101 104]
  ...
  [101 117 103 ... 120 129 134]
  [110 108 105 ... 126 123 131]
  [119  96 108 ... 125 120 130]]

 [[119 117 117 ... 104 105 109]
  [116 116 116 ... 104 104 106]
  [117 116 116 ... 102 102 105]
  ...
  [112 107 107 ... 120 126 132]
  [109 102 120 ... 123 125 132]
  [109 107 115 ... 122 124 126]]

 [[117 117 119 ... 103 107 115]
  [119 120 120 ... 103 107 116]
  [120 120 119 ... 105 108 116]
  ...
  [113 115  93 ... 126 135 141]
  [115 112 107 ... 123 131 142]
  [116 105 120 ... 125 129 140]]

 ...

 [[123 121 118 ... 111 111 113]
  [125 123 121 ... 107 107 109]
  [128 127 125 ... 104 105 108]
  ...
  [117 125 116 ... 124 130 139]
  [123 122 124 ... 121 130 139]
  [126 122 123 ... 122 133 139]]

 [[120 119 117 ... 114 113 114]
  [124 122 120 ... 108 109 112]
  [127 124 123 ... 105 106 110]
  ...
  [118 127 116 ... 125 130 138]
  [120 123 121 ... 122 129 138]
  [126 120 125 ... 121 130 1

In [2]:
import numpy as np


npz_path = '/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/landmarks/hangul_landmarks/오늘/test/오늘_00001.npz'

npz = np.load(npz_path, allow_pickle=True)['data']
for npy in npz:
    print(npy)
    break

[{'facial_landmarks': tensor([[[0.6471, 0.6471, 0.6471,  ..., 0.6039, 0.5961, 0.5961],
          [0.6471, 0.6471, 0.6471,  ..., 0.6157, 0.6078, 0.6078],
          [0.6471, 0.6471, 0.6471,  ..., 0.6157, 0.6078, 0.6078],
          ...,
          [0.2784, 0.2784, 0.2745,  ..., 0.2824, 0.3020, 0.2627],
          [0.2784, 0.2784, 0.2745,  ..., 0.2824, 0.3020, 0.2627],
          [0.2784, 0.2784, 0.2745,  ..., 0.2824, 0.3020, 0.2627]],

         [[0.7255, 0.7255, 0.7255,  ..., 0.6941, 0.6980, 0.6980],
          [0.7255, 0.7255, 0.7255,  ..., 0.6941, 0.6980, 0.6980],
          [0.7255, 0.7255, 0.7255,  ..., 0.6941, 0.6980, 0.6980],
          ...,
          [0.3490, 0.3490, 0.3451,  ..., 0.3686, 0.3490, 0.3098],
          [0.3490, 0.3490, 0.3451,  ..., 0.3686, 0.3490, 0.3098],
          [0.3490, 0.3490, 0.3451,  ..., 0.3686, 0.3490, 0.3098]],

         [[0.8667, 0.8667, 0.8667,  ..., 0.8510, 0.8549, 0.8549],
          [0.8667, 0.8667, 0.8667,  ..., 0.8549, 0.8549, 0.8549],
          [0.8667, 0.

In [3]:
import numpy as np
from PIL import Image

visual_data_path = '/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/datasets/visual_data/AFTERNOON/test/AFTERNOON_00001.npz'
landmarks_path = '/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/landmarks/LRW_landmarks/AFTERNOON/test/AFTERNOON_00001.npz'

npz = np.load(visual_data_path, allow_pickle=True)['data']
for i, npy in enumerate(npz):
    print(f'\n ------- {i} 번째 npy: {npy} -------')
    print(f'@#$#@$ npy.shape: {npy.shape}')
    print(f'@#$#@$ npy.shape 0: {npy.shape[0]}')
    print(f'@#$#@$ npy.shape 1: {npy.shape}')
    image = Image.fromarray(npy)
    image.save(f'/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/preprocessing/AFTERNOON/vis_AFTERNOON_00001_{i}.png')
    print(f'\n ------- vis 저장 완료 ------- \n')
    break

npz = np.load(landmarks_path, allow_pickle=True)['data']
for i, npy in enumerate(npz):
    print(f'\n ------- {i} 번째 npy: {npy} -------')
    print(f'@#$#@$ npy.shape: {npy.shape}')
    print(f'@#$#@$ npy.shape 0: {npy.shape[0]}')
    print(f'@#$#@$ npy.shape 1: {npy.shape}')
    # image = Image.fromarray(npy)
    # image.save(f'/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/preprocessing/AFTERNOON/land_AFTERNOON_00001_{i}.png')
    print(f'\n ------- land 저장 완료 ------- \n')
    break


 ------- 0 번째 npy: [[116 115 114 ... 102 103 109]
 [115 114 113 ... 102 102 107]
 [114 113 113 ... 102 101 104]
 ...
 [101 117 103 ... 120 129 134]
 [110 108 105 ... 126 123 131]
 [119  96 108 ... 125 120 130]] -------
@#$#@$ npy.shape: (96, 96)
@#$#@$ npy.shape 0: 96
@#$#@$ npy.shape 1: (96, 96)


FileNotFoundError: [Errno 2] No such file or directory: '/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/preprocessing/AFTERNOON/vis_AFTERNOON_00001_0.png'

In [14]:
import numpy as np
from utils import *  # utils.py 모듈에 있는 모든 함수 불러오기


# person_id = 0

# landmarks = [None] * 5
# facial_landmarks = {'facial_landmarks': landmarks}
# person_landmarks = [facial_landmarks] * 5
# multi_sub_landmarks = [person_landmarks] * 5

# landmarks_2 = [None] * len( multi_sub_landmarks)

# print('\n @@@@@ facial_landmarks: ', facial_landmarks)
# print('\n @@@@@ person_landmarks: ', person_landmarks)
# print('\n @@@@@ multi_sub_landmarks: ', multi_sub_landmarks)
# print()
# print('\n @@@@@ landmarks_2: ', landmarks_2)

# for frame_idx in range(len(multi_sub_landmarks)):
#     landmarks_2[frame_idx] = multi_sub_landmarks[frame_idx][person_id]['facial_landmarks']
#     print('\n ###########', frame_idx, landmarks_2[frame_idx])
#     break

###################################

# npz = np.array(multi_sub_landmarks)
SAVE_PATH = '/home/PHR/Lipreading_using_TCN_running/Lipreading_using_Temporal_Convolutional_Networks-master/preprocessing/test/test.npz'
# save2npz(SAVE_PATH,data=npz)

###################################

person_id = 0
multi_sub_landmarks = np.load(SAVE_PATH, allow_pickle=True)['data']
landmarks = [None] * len( multi_sub_landmarks)
for frame_idx in range(len(landmarks)):
    landmarks[frame_idx] = multi_sub_landmarks[frame_idx][int(person_id)]['facial_landmarks']
    print('@@@@@ landmarks[frame_idx]: ', landmarks[frame_idx])
    break
    

@@@@@ landmarks[frame_idx]:  [None, None, None, None, None]


In [24]:
import numpy as np

target = 29
n_frames = 53

x = np.linspace(1,2,10)  # 구간 시작점, 구간 끝점, 구간 내 숫자 개수
print('\n\n ### x: ', x)

idx = np.linspace(0,n_frames-1,29)
print('\n\n ### idx: ', idx)
print('\n ### len(idx): ', len(idx))
print('\n ### type(idx): ', type(idx))

idx = np.around(idx, 0).astype(np.int32)
print('\n\n ###### idx: ', idx)
print('\n ###### len(idx): ', len(idx))
print('\n ###### type(idx): ', type(idx))

print('\n ################################### \n')

target = 29
n_frames = 10

video_shape = (1080,1920,29)
output_video = np.zeros(video_shape).astype(np.uint8)
print('\n\n ### zero_padding: ', output_video)
print('\n ### len(zero_padding): ', len(output_video))
print('\n ### type(zero_padding): ', type(output_video))

# VIDEO_PATH = ''
# video = cv2.?
# output_video[:, :, :n_frames] = video
# for i in range(target-n_frames+1):
#     output_video[:, :, i+n_frames-1] = output_video[:, :, n_frames-1]
#     print(f'\n\n ###### {i}번째 output_video[:, :, n_frames-1]', output_video[:, :, n_frames-1])
#     print(f'\n ###### {i}번째 output_video[:, :, i+n_frames-1]', output_video[:, :, i+n_frames-1])



 ### x:  [1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


 ### idx:  [ 0.          1.85714286  3.71428571  5.57142857  7.42857143  9.28571429
 11.14285714 13.         14.85714286 16.71428571 18.57142857 20.42857143
 22.28571429 24.14285714 26.         27.85714286 29.71428571 31.57142857
 33.42857143 35.28571429 37.14285714 39.         40.85714286 42.71428571
 44.57142857 46.42857143 48.28571429 50.14285714 52.        ]

 ### len(idx):  29

 ### type(idx):  <class 'numpy.ndarray'>


 ###### idx:  [ 0  2  4  6  7  9 11 13 15 17 19 20 22 24 26 28 30 32 33 35 37 39 41 43
 45 46 48 50 52]

 ###### len(idx):  29

 ###### type(idx):  <class 'numpy.ndarray'>

 ################################### 



 ### zero_padding:  [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 

ValueError: could not broadcast input array from shape (3,) into shape (1080,1920,10)

In [4]:
import numpy as np
import os
from collections import deque

landmarks = np.array(
    [[[116 115 114 102 103 109],
  [115 114 113 102 102 107],
  [114 113 113 102 101 104],
  [101 117 103 120 129 134],
  [110 108 105 126 123 131],
  [119  96 108 125 120 130]]]
)
frame_idx = 0
print(f'--- landmarks: {landmarks}')

q_landmarks = deque()
print(f'--- q_landmarks: {q_landmarks}')
q_landmarks.append(landmarks[frame_idx])
print(f'--- q_landmarks: {q_landmarks}')
smoothed_landmarks = np.mean(q_landmarks, axis=0)
print(f'--- smoothed_landmarks: {smoothed_landmarks}')

--- landmarks: [[1 2 3]
 [4 5 6]]
--- q_landmarks: deque([])
--- q_landmarks: deque([array([1, 2, 3])])
--- smoothed_landmarks: [1. 2. 3.]
